### ISSUE TITLE
when installed via npm /lib folder is missing

### ISSUE THREAD

**Issue by simonghales** [elrumordelaluz/coloreact#1]
Hey mate,

I'm trying to install this via NPM but it seems the /lib folder is missing.

Your package.json references `"main": "lib/index.js",`

but when viewing the installed folder within `node_modules/coloreact` only docs, examples, node_modules and src are present.

**Comment by elrumordelaluz** [comment]
Hi @simonghales, thanks for report this issue and I'm sorry for the delay.
Should be solved in `v0.1.9`. Let me know plz.

**Comment by simonghales** [comment]
Seems to be sorted, cheers!
