### ISSUE TITLE
License and attribution

### ISSUE THREAD

**Issue by WickyNilliams** [elrumordelaluz/coloreact#2]
Hey.

I stumbled across your project and noticed that it is a derivative of [my color picker for react](https://github.com/WickyNilliams/react-simple-colorpicker), which itself was a derivative of [this other colorpicker for react](https://github.com/stayradiated/react-colorpicker).

In case you weren't aware, the MIT license - which both of those projects are licensed under - requires that you preserve the original copyright notice. You are free to fork, modify etc the code subject to that one condition.

As such, it would be cool if you could add appropriate attribution to @stayradiated and myself. Not sure whether the ISC license (which you list in package.json) is compatible with MIT, so you may want to investigate that or revert simply back to MIT.

**Comment by WickyNilliams** [comment]
Thank you :) 

I *think* you need a file containing the full license text e.g. https://github.com/WickyNilliams/react-simple-colorpicker/blob/master/LICENSE

**Comment by elrumordelaluz** [comment]
@WickyNilliams you are absolutely right.

Hope the last commit fix the issue.
At the moment I started using your awesome project and found a bunch of stuff didn't work for my _use case_. Found easier to re-create with my owns needs solved.

At the moment don't have time but I think could be interesting to tell you all the stuff I needed to re-think, maybe to  improve, maybe to exchange ideas, maybe to (in case) merge stuff in an _unique_ project.

I'm sorry for the distraction in not include _Attributions_ at the moment. 
Let's chat in case.

**Comment by elrumordelaluz** [comment]
[Added](https://github.com/elrumordelaluz/coloreact/blob/master/LICENSE), thanks again.

**Comment by WickyNilliams** [comment]
@elrumordelaluz i have no problem with you forking for your own needs, that's the beauty of open source :) And that's exactly why I forked stayradiated's repo originally.

I'd very much appreciate any ideas or thoughts you have, whenever you have time. After forking stayradiated's repo, I did the exact same thing - created some issues with ideas/suggestions for improvements. As the saying goes: a rising tide lifts all boats :)

**Comment by elrumordelaluz** [comment]
absolutely!

**Comment by WickyNilliams** [comment]
I hope my original issue didn't come across badly. Thanks again for doing this and being so polite about it. <3

**Comment by elrumordelaluz** [comment]
Absolutely not. Will try to go back into the issue, maybe update also the `clone` and give you some feedback.
