### ISSUE TITLE
TS7027 TypeScript Unreachable code detected.

### ISSUE THREAD

**Issue by mario-insegna** [elrumordelaluz/coloreact#3]
Hi, I am using your component, and I found an issue in ColorPicker class on this function:
  output () {
    const c = tinycolor(this.state.color);
    return {
      hsl: c.toHsl(),
      hex: c.toHex(),
      hexString: c.toHexString(),
      rgb: c.toRgb(),
      rgbString: c.toRgbString(),
    }
    return c;
}
Could you please, remove the second return, so I can use it alongside TypeScript? 
Thank you.

**Comment by elrumordelaluz** [comment]
good catch! thank you @mario-insegna
