### ISSUE TITLE
Yellow section of Hue Slider too small.

### ISSUE THREAD

**Issue by feluxe** [elrumordelaluz/coloreact#6]
Hi there, thanks for sharing this. I love this package, because it allows me to customize every bit quite easily.

There is one thing I've noticed for the default Hue Pickers: The yellow sections is rather small, so it's difficult to pick a pure yellow.

The current Slider uses this:

```
#FF0000 0%,
#FF0099 10%,
#CD00FF 20%,
#3200FF 30%,
#0066FF 40%,
#00FFFD 50%,
#00FF66 60%,
#35FF00 70%,
#CDFF00 80%,
#FF9900 90%,
#FF0000 100%
```
I think these values work a little nicer (taken from here: https://github.com/casesandberg/react-color/blob/master/src/components/common/Hue.js) 

```
#f00 0%, 
#ff0 17%, 
#0f0 33%,
#0ff 50%, 
#00f 67%, 
#f0f 83%, 
#f00 100%
```
I'd suggest using those for the default pickers.

Cheers! :-)

**Comment by elrumordelaluz** [comment]
Hi @feluxe, thanks for open the _Issue_ and for pointing that!
Do you mind open a PR with those changes?

Thanks!
